name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_IMAGE_REFERENCE: ${{ vars.APP_PARTIAL_IMAGE_REFERENCE }}/app:${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build and test
        run: ./gradlew build

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.GCP_CI_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ vars.GCP_CI_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ vars.APP_REGISTRY_HOSTNAME }} --quiet

      - name: Build and push Docker image
        working-directory: source
        run: |
          docker build -t ${{ env.APP_IMAGE_REFERENCE }} .
          docker push ${{ env.APP_IMAGE_REFERENCE }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14"

      - name: Terraform Init
        working-directory: infra/support
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TERRAFORM_GCS_STATE_BUCKET_NAME }}"

      - name: Terraform Apply
        working-directory: infra/support
        run: |
          terraform apply -auto-approve \
            -var="terraform_state_bucket_name=${{ vars.TERRAFORM_GCS_STATE_BUCKET_NAME }}"
            -var="app_image_reference=${{ env.APP_IMAGE_REFERENCE }}"
